// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------，，。，，。。。，，，， 。，。------------------------------------
/**
 * Emory He
 */
/************************************************************/
/**
 * Represents a chip/game piece
 */
public class Dot {
	/**
	 * int represents which player the dot belongs to
	 */
	public int type_;

	/**
	 * Creates an instance of a Dot and initializes its type to 0.
	 */
	public Dot () {
		type_ = 0;
	}

	/**
	 * Returns an int representing the ownership of the Dot. 0 means no one. 1 and
	 * 2 correspond to the players
	 * 
	 * @return this dot's type
	 */
	public int getType () {
		return type_;
	}

	/**
	 * Sets the ownership of the Dot
	 * 
	 * @param type for dot to be set to
	 */
	public void setType ( int type ) {
		type_ = type;
	}

}
