// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/**
 * Emory
 */
/************************************************************/
/**
 * Handles display of board and user interaction (implements mouse listener)
 */
public class DrawPanel {
	/**
	 * draw panel’s game object to manipulate
	 */
	private Game game_;
	/**
	 * 
	 */
	public Game game;

	/**
	 * draws the board
	 */
	public void drawBoard () {}
};
